version: '2'
services:
  openvpn:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: openvpn
    image: openvpn:latest
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    environment:
      - EASYRSA_KEY_SIZE=4096
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    restart: always
